# Generated by Django 4.2.14 on 2024-08-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Description',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Link',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link_preview',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
